### PR TITLE
github: switch to use lxc

### PR DESCRIPTION
**Pull request by kenhys**
vagrant on macos is fragile recently, try to use lxc.

### CODE REVIEW

**Comment by kenhys** [comment]
This is WIP to check whether it is available.

**Comment by daipom** [comment]
Great!! We have to fix the current unstable CI. Thanks!
I'll consider it too!

**Comment by kenhys** [comment]
https://github.com/fluent/fluent-package-builder/actions/runs/7137422452/job/19437720881
Except on AmazonLinux 2023, it seems work expectedly.

**Comment by kenhys** [comment]
waiting CI.

**Comment by kenhys** [comment]
deb and rpm CI has passed.

**Comment by kenhys** [comment]
@daipom all checks has passed!

**Review by daipom — APPROVED** [review]
Great! Thanks! LGTM!

**Comment by daipom** [comment]
Note: We can remove [Vagrantfile](https://github.com/fluent/fluent-package-builder/blob/b793ab1d9632d66b14d19a3c302332bf1237c11d/Vagrantfile), but it may be useful to use the environments locally.
It would be fine to leave it for now.

**Comment by daipom** [comment]
@kenhys This will be squash-merged.
If there is any information that should be kept from each commit message, I'd appreciate it if you could summarize it in the first comment of the PR.

**Pull request merged**
